### ISSUE TITLE
Discuss self reporting and peer requests

### ISSUE THREAD

**Issue by itsnehasharma** [SarahBrown97/GatorMind#12]
Discuss with group 4 and group 5 about the different types of self reporting, how peer-support could be implemented and how the data is sent from them, so that we can take actions on our end.

Group 4, 5 - Discuss how the dashboard team (group 4) and the intervention team (group 5) are going to send the Self reporting and peer-support requests.

**Comment by comfort48** [comment]
From group-3's perspective - we had discussed with group-5 and agreed upon protocol for the communication channel b/w the 2 groups. We are closely working with group-5.

**Comment by comfort48** [comment]
Closing this issue as the discussion and implementation has been done.
