### ISSUE TITLE
Illustrate Dashboard Interfaces

### ISSUE THREAD

**Issue by itsnehasharma** [SarahBrown97/GatorMind#22]
Due 11/19 for project presentation
Illustrate all the interfaces that are part of the dashboard (eg. log in, just logged in, health care worker home page, search results for multiple patients, single patient showing all visualized biometrics) - simple portrayal of how pages look & be able to share with the class; can be done with pencil & paper, or however the group wants to display. This will be presented in Thursday's presentation.

**Comment by sayedafif** [comment]
Version 1 of the interfaces are developed. So, closing this issue.
